### ISSUE TITLE
Optional trailing slash support

### ISSUE THREAD

**Issue by dalberto** [phpdude/django-macros-url#6]
In the same way that a trailing `$` is added to every regex, it would be useful add a `/?`. This would make  a trailing slash optional. This behavior may be unexpected so I imagine every Macro would need to be tweakable.

**Comment by phpdude** [comment]
Hi Darlin,

I think it is not good idea because for search engines "/page/" and "/page" are different. This can be added only as option, better is to use append slash django feature (https://docs.djangoproject.com/en/1.9/ref/settings/#append-slash). 

But anyway it is good idea, I will think (and will read django source code) about it.

Thanks!

**Comment by dalberto** [comment]
Thanks for the speedy reply.
On second thought, I suppose this is unnecessary because a macro can be written for the optional trailing slash. I'm not sure if this will have unknown side-effects.

**Comment by phpdude** [comment]
@dalberto yes it can of course. But I am not sure it is good way, please check APPEND_SLASH django feature.

**Comment by phpdude** [comment]
https://github.com/django/django/blob/master/django/middleware/common.py#L69

**Comment by phpdude** [comment]
Django handles this best way I think ;)

https://github.com/django/django/blob/master/django/middleware/common.py#L39

**Comment by dalberto** [comment]
Oh, thanks! Sorry for the extraneous request, feel free to close this issue.

**Comment by phpdude** [comment]
Only one stuff can be done - auto trailing slash (strict, all urls ends with "/") to make all urls more elegant and allow developer forget about trailing slashes at all.

**Comment by phpdude** [comment]
I double checked source code, looks like force add slash to end of rule is bad idea because user will not have any chance to remove it, only hacks like `str(url(..))` but it is ugly for me and I don't want to do it. So I close the issue.

Anyway thanks for your ideas.

**Comment by dalberto** [comment]
Thanks for your help nevertheless. This library has proven very useful!

**Comment by phpdude** [comment]
@dalberto I wait when it will be native in Django (or any alternative) because it is simple and covers 90% of user cases, but anyway, it is small, clear and integrated very well into Django, so I start all my projects from installing macros library :)
