### ISSUE TITLE
url() got an unexpected keyword argument 'prefix'

### ISSUE THREAD

**Issue by Grmiade** [phpdude/django-macros-url#7]
I have this error `url() got an unexpected keyword argument 'prefix'` with Django 1.10.3. An idea?

<img width="1052" alt="capture d ecran 2016-11-08 a 17 40 04" src="https://cloud.githubusercontent.com/assets/11244106/20107884/6c7ac6e4-a5da-11e6-9e94-8383c17eb917.png">

**Comment by phpdude** [comment]
@Grmiade added support for Django 1.10 in 0.3.0 version (commit url https://github.com/phpdude/django-macros-url/commit/2ff37b88e410dd744646c79f9c9bd71836215122).

Once it will be tested with Travis, I will publish new version to Pypi

**Comment by phpdude** [comment]
Looks like it is passed all tests, so ... publishing :) 

https://travis-ci.org/phpdude/django-macros-url/builds/174930428

**Comment by phpdude** [comment]
ok, published sdist + wheel version now at https://pypi.python.org/pypi/django-macros-url
